//<![CDATA[
(function(a){a.organicTabs=function(c,b){var d=this;d.$el=a(c);d.$nav=d.$el.find(".navtab");d.init=function(){d.options=a.extend({},a.organicTabs.defaultOptions,b);a(".hide").css({position:"relative",top:0,left:0,display:"none"});d.$nav.delegate("li > a","click",function(){var g=d.$el.find("a.current").attr("href").substring(1),f=a(this),e=f.attr("href").substring(1),h=d.$el.find(".list-tabwrap"),i=h.height();h.height(i);if((e!=g)&&(d.$el.find(":animated").length==0)){d.$el.find("#"+g).fadeOut(d.options.speed,function(){d.$el.find("#"+e).fadeIn(d.options.speed);var j=d.$el.find("#"+e).height();h.animate({height:j});d.$el.find(".navtab li a").removeClass("current");f.addClass("current")})}return false})};d.init()};a.organicTabs.defaultOptions={speed:300};a.fn.organicTabs=function(b){return this.each(function(){(new a.organicTabs(this,b))})}})(jQuery);    
//
$(document).ready(function(){$("#showparser").click(function(){$("#parser").slideToggle("slow")})});
function convert(){var ele1 = document.getElementById("somewhere");var replaced;replaced = ele1.value;replaced = replaced.replace(/&/ig, "&amp;");replaced = replaced.replace(/</ig, "&lt;");replaced = replaced.replace(/>/ig, "&gt;");replaced = replaced.replace(/"/ig, "&quot;");replaced = replaced.replace(/&#177;/ig, "&plusmn;");replaced = replaced.replace(/&#169;/ig, "&copy;");replaced = replaced.replace(/&#174;/ig, "&reg;");replaced = replaced.replace(/ya'll/ig, "ya'll");ele1.value = replaced;};
window.onload=function(){setTimeout(function(){var e=document.querySelector("ins.adsbygoogle");e&&0==e.innerHTML.replace(/\s/g,"").length&&(e.style.cssText="color:rgba(0,0,0,0.5);font-weight:700;font-size:110%;padding:20px;margin:auto;text-align:center;text-decoration:none;display:block!important;background:rgba(0,0,0,0.02);border:1px solid rgba(0,0,0,0.08)",e.innerHTML="")},2e3)};
$(function(){$(".menu-notif").on("click",function(){$(".notif-blanter").addClass("active").find(".search").focus()});$(".notif-blanter").on("click",function(){$(this).find(".search").focus()});$(".notif-close").on("click",function(){$(".notif-blanter").removeClass("active")})});
window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":"http://bulshitman.blogspot.co.id/p/privacy-policy-for-bulshitman.html","theme":"light-bottom"};
(function(){var e=document.createElement("script");e.async=true;e.type="text/javascript";e.src="http://yourjavascript.com/8191175451/cookieconsent.js";(document.getElementsByTagName("HEAD")[0]||document.getElementsByTagName("BODY")[0]).appendChild(e)})();
//]]>
